### ISSUE TITLE
Add userId inside the rego input

### ISSUE THREAD

**Issue by davidebianchi** [rond-authz/rond#207]
To get the userId, at the moment I must have it in headers and get it from the headers.
But rond already take it from the header, so we could add it in the `InputUser` struct to simplify the get of the user id.

**Describe the solution you'd like**
Add the userId in this struct https://github.com/rond-authz/rond/blob/67adb740953c2cd5e86ac4d9ceefb1b70ffd5ee4/core/input.go#L52-L58

**Describe alternatives you've considered**
It's possible at the moment to take it from headers, but it's a duplication from what rond already do.

**Comment by tarunsamanta2k20** [comment]
I'd like to work on it.

**Comment by fredmaggiowski** [comment]
Hi @davidebianchi yes, I agree with you; this makes sense and may be useful to folks out there; let's do it!

Thank you @tarunsamanta2k20, it should be pretty straightforward if you want to give it a try just submit a PR :)

**Comment by fredmaggiowski** [comment]
I've managed to complete the implementation in a new PR, sorry @tarunsamanta2k20 I saw your PR was stalling and thought it was faster implementing it a new PR, thanks for the attempt anyway :)
