### ISSUE TITLE
Decouple web server status routes permission precomputation

### ISSUE THREAD

**Issue by fredmaggiowski** [rond-authz/rond#268]
#### Is your feature request related to a problem? Please describe

Often times on Kubernetes, when there are several policies to be evaluated at startup, the service may take a while to startup and, attaching liveness probes on the `/-/rbac-healthz` route without a very high threshold may lead the service to be killed.

#### Describe the solution you'd like

Decouple probes from web server startup

- `/-/rbac-ready`, commonly attached to the readiness probe, immediately replies but only returns 200 after precomputation is completed
-  `/-/rbac-healthz`, commonly attached to the liveness probe,  immediately replies and returns 200 since the service is up and running
- adding a `/-/rbac-startup`, commonly attached to the startup probe, that behaves as the readiness route.

#### Describe alternatives you've considered

Current solution are:

  - disabling probes
  - tune liveness probe configuration to fail after a pretty long time
  - configure a startup probe on the healthz route

**Comment by fredmaggiowski** [comment]
@pmarchini FYI

**Comment by davidebianchi** [comment]
Hi @fredmaggiowski! From the K8s documentation, the startup probe should be equal to the check used for the liveness probe with different failureTreshold and periodSecond values to cover the worst case startup time ([link to docs](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-startup-probes)). 
So, why add a new route? I think that the better think is to call the already existent /-/rbac-healtz route and configure the service on K8s accordingly.
What do you think about?

**Comment by fredmaggiowski** [comment]
I didn't know this doc, thanks for sharing it; while I know the practice of linking it to the same liveness mechanism I'm still not sure that it would be the correct solution for this web service.

Since startup probe is meant to cover services with a long warmup I'd see this probe used to make sure the service is actually up and running, to match this criteria it would mean that the service has precomputed everything (aka: it is ready)

TBH, I'm still uncertain about the need for a new API; you could still link the startup probe the one you desire (either the ready or the healthz) based on the use case or belief but I'm more keen to be more semantic and provide the API as well.

In the end I'm sure we need to decouple web service startup from the currently existing probe and I think I'll open a PR soon with a proposal on this; for the startup probe we can discuss it a little bit and pick the right decision

**Comment by davidebianchi** [comment]
Mmh I think that startup probe is needed just to resolve this decoupling in an easy way (it's the "trick" said in the previous linked docs for this service case). 
If I correctly understand, the decoupling is intended to respond 200 at the liveness probe as soon as possible (so without await the end of pre-computation) and flag the service as ready only after that. Is it correct?
In this case, the startup probe would not need (since it delay the liveness check). 
It should be checked the rolling update, but it should work correctly I suppose.

**Comment by fredmaggiowski** [comment]
> If I correctly understand, the decoupling is intended to respond 200 at the liveness probe as soon as possible (so without await the end of pre-computation) and flag the service as ready only after that. Is it correct?

Yes this is what I'm looking forward to

>Mmh I think that startup probe is needed just to resolve this decoupling in an easy way (it's the "trick" said in the previous linked docs for this service case).
>...
> In this case, the startup probe would not be needed(since it delays the liveness check).

I agree, I just like the service to be "explicit" on how you should consider it alive/ready but I think the two endpoints are more than enough for any sort of integration


> It should be checked the rolling update, but it should work correctly I suppose.

Why you think this may be an issue? The service won't shut the readiness route and still receive traffic, until the server is shutdown for the SIGTERM 🤔

**Comment by davidebianchi** [comment]
When rolling, it is possible to that the old service it's killed before the new service is ready? I don't think so, but if the ready time for the service is very long, this could be an issue? Also, I don't think so since the rolling is based on the readiness, but maybe a manual test to verify it would be better.

**Comment by fredmaggiowski** [comment]
>When rolling, it is possible that the old service is killed before the new service is ready?  I don't think so, but if the ready time for the service is very long, this could be an issue?

This should not happen, the service old pods get killed when the new ones are _ready_ to receive requests even if takes a lot of time

>Also, I don't think so since the rolling is based on the readiness, but maybe a manual test to verify it would be better.

For sure we will have to take a look at how it behaves
