### ISSUE TITLE
Inject custom data into policies via environment or secret variables

### ISSUE THREAD

**Issue by galatifederico** [rond-authz/rond#346]
#### Is your feature request related to a problem? Please describe
It would be useful to be able to use values via secret or environmental variables in rond policies. Currently if I have to define policies that needs to use sensitive data I cannot do that in a secure way.

#### Describe the solution you'd like

I would like to use environment variables o secrets that can be used inside the policies.

**Comment by fredmaggiowski** [comment]
Hi @galatifederico this is an extremely interesting feature, it is actually already tracked by #343 

I'm closing this as duplicate :)
